### ISSUE TITLE
failed to package into app

### ISSUE THREAD

**Issue by jhoogeboom** [jingweno/hacker-menu#22]
This is what I get when running `npm run release`
```
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hacker-menu@1.1.3 release script 'npm run package && npm run compress'.
npm ERR! This is most likely a problem with the hacker-menu package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run package && npm run compress
npm ERR! You can get their info via:
npm ERR!     npm owner ls hacker-menu
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jorishoogeboom/Downloads/hacker-menu-master/npm-debug.log
```
npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'release' ]
2 info using npm@2.14.2
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
6 info prerelease hacker-menu@1.1.3
7 info release hacker-menu@1.1.3
8 verbose unsafe-perm in lifecycle true
9 info hacker-menu@1.1.3 Failed to exec release script
10 verbose stack Error: hacker-menu@1.1.3 release: `npm run package && npm run compress`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid hacker-menu@1.1.3
12 verbose cwd /Users/jorishoogeboom/Downloads/hacker-menu-master
13 error Darwin 14.5.0
14 error argv "node" "/usr/local/bin/npm" "run" "release"
15 error node v0.12.7
16 error npm  v2.14.2
17 error code ELIFECYCLE
18 error hacker-menu@1.1.3 release: `npm run package && npm run compress`
18 error Exit status 1
19 error Failed at the hacker-menu@1.1.3 release script 'npm run package && npm run compress'.
19 error This is most likely a problem with the hacker-menu package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     npm run package && npm run compress
19 error You can get their info via:
19 error     npm owner ls hacker-menu
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by lokywin** [comment]
I get error from `npm run release` as well. May not be related.
```
Packaging app for platform darwin x64 using electron v0.31.2
Command failed: /bin/sh -c codesign --deep --force --sign "Developer ID Application: Jingwen Ou" "/var/folders/hn/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/T/electron-packager/darwin-x64/Hacker Menu-darwin-x64/Hacker Menu.app"
Developer ID Application: Jingwen Ou: no identity found
```

**Comment by jhoogeboom** [comment]
yes that's also what appears with me, forgot to paste that in.

**Comment by jingweno** [comment]
@jhoogeboom That's because you don't have the cert to sign the app and the build process is [hardcoded to sign the app](https://github.com/jingweno/hacker-menu/blob/master/script/package.sh#L22). A easy workaround is to set the `CI` environment variable to true: `CI=true npm run release`. I will push a change later to make signing optional.

**Comment by jingweno** [comment]
I just made a changes that you can directly run `npm run package` without a cert to sign the app. Don't run `npm run release` which runs package in signing mode.
